### ISSUE TITLE
Broken build with "generate-bindings" feature "error: environment variable `OUT_DIR` not defined

### ISSUE THREAD

**Issue by inferrna** [katyo/oboe-rs#1]
```bash
error: environment variable `OUT_DIR` not defined
 --> /home/inferno/.cargo/registry/src/github.com-1ecc6299db9ec823/oboe-sys-0.1.0/src/lib.rs:9:18
  |
9 | include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
  |    
```
Build command:
```bash
cargo build --target arm-linux-androideabi
```

**Comment by katyo** [comment]
This is so strange because `OUT_DIR` should be set by Cargo in any case.
See https://doc.rust-lang.org/1.30.0/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates

**Comment by inferrna** [comment]
My android app based on https://github.com/Dushistov/rust_swig crate. I just added your "play sine" example to it's example app and got the same error. Can you please look on it?
https://github.com/inferrna/rust_swig

**Comment by katyo** [comment]
@inferrna It seems I fixed this.
I had missing "build.rs" listed in 'include' field in cargo manifest, so cargo had not add build script to package on publishing.

v0.2.1 should works as expected

**Comment by katyo** [comment]
I have tried to use __flapigen__ with my app.
It compiles and works fine.
