### ISSUE TITLE
No bindings when build from git

### ISSUE THREAD

**Issue by inferrna** [katyo/oboe-rs#3]
**Config:**
```cargo
oboe = { git = "https://github.com/katyo/oboe-rs.git" }
```
**Output:**
```bash
/home/inferno/.cargo/git/checkouts/oboe-rs-d5611afad1477cfd/8bf93ee/oboe-sys/src/bindings_armv7.rs: No such file or directory (os error 2)
```

**Comment by katyo** [comment]
Of course, it because I doesn't planned to track generated bindings by git.
But I can add this when needed. Right?

**Comment by inferrna** [comment]
You can even to automate it. For example - check exists of bindings in `build.rs`.

**Comment by katyo** [comment]
Hmm, interesting idea.
