### ISSUE TITLE
CI Failure from Java SDK issue?

### ISSUE THREAD

**Issue by tibbon** [katyo/oboe-rs#54]
https://github.com/katyo/oboe-rs/actions/runs/5722460773/job/15505550055

I hope my commit merged didn't cause this. I don't Java much, so debugging this is a bit out of my realm of expertise.

**Comment by tibbon** [comment]
I could imagine the fix will have some similar aspects of this
https://github.com/katyo/oboe-rs/pull/49/files

**Comment by katyo** [comment]
@tibbon Currently I have strange linking issues with latest LTS NDK in CI (See PR #55)

**Comment by katyo** [comment]
Fixed by #55
