### ISSUE TITLE
Wrap getTimestamp()

### ISSUE THREAD

**Issue by endragor** [katyo/oboe-rs#9]
getTimestamp() is useful for some applications. It'd be better to use it in CPAL rather than compute time based on frame count and sample rate.

**Comment by katyo** [comment]
Are you mean [AudioStream::get_timestamp()](https://docs.rs/oboe/0.1.0/oboe/trait.AudioStream.html#tymethod.get_timestamp)?

**Comment by endragor** [comment]
Ah, I forgot it exists for the basic streams. I meant to add it to the streams passed to callbacks, i.e. [AudioInputStream](https://docs.rs/oboe/0.1.0/oboe/trait.AudioInputStream.html) and [AudioOutputStream](https://docs.rs/oboe/0.1.0/oboe/trait.AudioOutputStream.html). Right now there is only `get_frames_read` and `get_frames_written`.

**Comment by katyo** [comment]
IIRC my design `AudioStream` trait is also implemented for streams available in callbacks.

**Comment by endragor** [comment]
The callback accepts `&mut dyn AudioInputStream`: https://docs.rs/oboe/0.1.0/oboe/trait.AudioInputCallback.html#tymethod.on_audio_ready

I don't see how to access `get_timestamp` from there.

**Comment by katyo** [comment]
The `AudioInputStream` trait should implements `AudioStream`. See definition.

**Comment by endragor** [comment]
Ah indeed. So this particular request is already implemented. One improvement could be for the callbacks to provide only a subset of API that is safe to invoke callbacks. Currently you may invoke write operations from callbacks, which is unsafe to do, according to the docs.

**Comment by katyo** [comment]
> Ah indeed. So this particular request is already implemented. One improvement could be for the callbacks to provide only a subset of API that is safe to invoke callbacks. Currently you may invoke write operations from callbacks, which is unsafe to do, according to the docs.

Of course, it would be good to change this in future. I just followed C++ API when implement bindings.
